-- Create tables for OTT Aggregator

-- 1. Works Table (Minimalist + Production Info)
create table public.works (
  id uuid default gen_random_uuid() primary key,
  tmdb_id integer unique not null,
  title text not null,
  original_title text,
  release_year integer,
  genres text[], -- Array of strings e.g. ['Action', 'Drama']
  production_countries text[], -- Array of strings e.g. ['KR', 'US']
  production_companies text[], -- Array of strings e.g. ['Studio Dragon', 'Netflix']
  popularity numeric,
  type text, -- 'movie' or 'tv'
  overview text,
  poster_path text,
  backdrop_path text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Platforms Table
create table public.platforms (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique, -- e.g. 'netflix', 'wavve'
  logo_path text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Availability Table (The Core Relationship)
create table public.availability (
  id bigint generated by default as identity primary key,
  work_id uuid references public.works(id) on delete cascade not null,
  platform_id bigint references public.platforms(id) on delete cascade not null,
  link text, -- Deep link to the content
  is_exclusive boolean default false,
  service_start_date date, -- For "New Arrivals"
  service_end_date date,   -- For "Leaving Soon"
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(work_id, platform_id)
);

-- 4. Enable Row Level Security (RLS)
-- Allow read access to everyone, write access only to service_role (backend scripts)
alter table public.works enable row level security;
alter table public.platforms enable row level security;
alter table public.availability enable row level security;

create policy "Enable read access for all users" on public.works for select using (true);
create policy "Enable read access for all users" on public.platforms for select using (true);
create policy "Enable read access for all users" on public.availability for select using (true);

-- Indexes for performance
create index idx_works_tmdb_id on public.works(tmdb_id);
create index idx_availability_dates on public.availability(service_end_date, service_start_date);

-- Insert default platforms (Korean Context)
insert into public.platforms (name, slug) values 
('Netflix', 'netflix'),
('Watcha', 'watcha'),
('Wavve', 'wavve'),
('Disney Plus', 'disney'),
('Coupang Play', 'coupang'),
('Tving', 'tving'),
('Apple TV Plus', 'apple'),
('Amazon Prime Video', 'amazon'),
('Laftel', 'laftel')
on conflict (name) do nothing;
